POST http://localhost:8080/farm/41caae5d-2bda-4849-abb0-f0295b1af0f8/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJib29tZXJtYXRoIiwibmJmIjoxNzAxMjExMDcxLCJyb2xlcyI6W10sImlzcyI6ImZhcm1lZCIsImlkIjoiMmJlNTRkNmQtZTBmMi00ODE3LTkwODUtOTBkZGZlMTIxMDNhIiwiZXhwIjoxNzAxMjE0NjcxLCJpYXQiOjE3MDEyMTEwNzF9.SDudZxZ2xDHdDduScexoWi2e_7VfaVasWTFlfQ6hklM

{
  "stars": 3,
  "text": "my review is awesome!"
}